#!/usr/bin/env python3
"""Extract per-layer quantization parameters from RKNN IR and TFLite, compare them.

Runs inside the rknn-sim Docker container:
  docker run --rm -v "$(pwd):/data" rknn-sim python3 /data/extract_quant_params.py

The RKNN post-fusion IR (154 nodes) has empty quant annotations for QAT models.
Instead, we use check0_base_optimize.onnx which preserves QuantizeLinear/DequantizeLinear
nodes with the original scale/zero_point values from TFLite conversion.
"""

import json
import os
import sys
import numpy as np


def build_rknn_and_get_onnx(tflite_path):
    """Run RKNN build to generate check0_base_optimize.onnx, return path."""
    onnx_path = 'check0_base_optimize.onnx'
    if os.path.exists(onnx_path):
        print(f'Using existing {onnx_path}')
        return onnx_path

    from rknn.api import RKNN
    rknn = RKNN(verbose=False)
    rknn.config(target_platform='rk3588',
                quantized_dtype='asymmetric_quantized-8',
                quantized_algorithm='normal',
                quantized_method='channel')
    ret = rknn.load_tflite(model=tflite_path)
    if ret != 0:
        print(f'load_tflite failed: {ret}', file=sys.stderr)
        sys.exit(1)
    ret = rknn.build(do_quantization=False)
    if ret != 0:
        print(f'build failed: {ret}', file=sys.stderr)
        sys.exit(1)
    rknn.release()

    if not os.path.exists(onnx_path):
        print(f'ERROR: {onnx_path} not generated by RKNN build', file=sys.stderr)
        sys.exit(1)
    return onnx_path


def extract_rknn_params(onnx_path):
    """Extract per-Conv quant params from the pre-fusion ONNX graph."""
    import onnx
    from onnx.numpy_helper import to_array

    model = onnx.load(onnx_path)
    graph = model.graph

    # Build initializer lookup
    inits = {}
    for init in graph.initializer:
        try:
            inits[init.name] = to_array(init)
        except Exception:
            inits[init.name] = None

    # Build output->node map
    output_to_node = {}
    for i, n in enumerate(graph.node):
        for o in n.output:
            output_to_node[o] = (i, n)

    # Build input consumer map (tensor_name -> list of nodes that consume it)
    input_consumers = {}
    for n in graph.node:
        for inp in n.input:
            input_consumers.setdefault(inp, []).append(n)

    from collections import Counter
    op_types = Counter(n.op_type for n in graph.node)
    print(f'RKNN ONNX ({onnx_path}): {len(graph.node)} nodes')
    print(f'  Op types: {dict(op_types)}')

    conv_ops = []
    for idx, node in enumerate(graph.node):
        if node.op_type != 'Conv':
            continue

        entry = {
            'rknn_node_index': idx,
            'name': node.name[:80],
        }

        # Extract activation quant params (from DequantizeLinear feeding input 0)
        act_input = node.input[0]
        if act_input in output_to_node:
            src_idx, src_node = output_to_node[act_input]
            if src_node.op_type == 'DequantizeLinear':
                scale = inits.get(src_node.input[1])
                zp = inits.get(src_node.input[2]) if len(src_node.input) > 2 else None
                entry['input_scale'] = float(scale) if scale is not None else None
                entry['input_zp'] = int(zp) if zp is not None else None

        # Extract weight quant params (from DequantizeLinear feeding input 1)
        weight_input = node.input[1]
        if weight_input in output_to_node:
            src_idx, src_node = output_to_node[weight_input]
            if src_node.op_type == 'DequantizeLinear':
                scale = inits.get(src_node.input[1])
                zp = inits.get(src_node.input[2]) if len(src_node.input) > 2 else None
                if scale is not None:
                    entry['weight_scales'] = scale.flatten().tolist()
                if zp is not None:
                    entry['weight_zps'] = zp.flatten().tolist()
                # Get actual weight shape from the QuantizeLinear input
                # DequantizeLinear input[0] is the quantized weight tensor
                qw_name = src_node.input[0]
                qw = inits.get(qw_name)
                if qw is not None:
                    entry['weight_shape'] = list(qw.shape)
                    entry['weight_dtype'] = str(qw.dtype)

        # Extract bias quant params (from DequantizeLinear feeding input 2)
        if len(node.input) > 2:
            bias_input = node.input[2]
            if bias_input in output_to_node:
                src_idx, src_node = output_to_node[bias_input]
                if src_node.op_type == 'DequantizeLinear':
                    scale = inits.get(src_node.input[1])
                    if scale is not None:
                        entry['bias_scales'] = scale.flatten().tolist()

        # Extract output quant params (from QuantizeLinear consuming conv output)
        conv_output = node.output[0]
        for consumer in input_consumers.get(conv_output, []):
            if consumer.op_type == 'QuantizeLinear':
                scale = inits.get(consumer.input[1])
                zp = inits.get(consumer.input[2]) if len(consumer.input) > 2 else None
                entry['output_scale'] = float(scale) if scale is not None else None
                entry['output_zp'] = int(zp) if zp is not None else None
                break
        else:
            # Output may go through Relu first, then QuantizeLinear
            for consumer in input_consumers.get(conv_output, []):
                if consumer.op_type == 'Relu':
                    relu_out = consumer.output[0]
                    for consumer2 in input_consumers.get(relu_out, []):
                        if consumer2.op_type == 'QuantizeLinear':
                            scale = inits.get(consumer2.input[1])
                            zp = inits.get(consumer2.input[2]) if len(consumer2.input) > 2 else None
                            entry['output_scale'] = float(scale) if scale is not None else None
                            entry['output_zp'] = int(zp) if zp is not None else None
                            break

        # Print summary
        n_ws = len(entry.get('weight_scales', []))
        w_shape = entry.get('weight_shape', [])
        print(f'  [{idx:3d}] Conv  w_shape={w_shape} '
              f'w_scales={n_ws} '
              f'in_s={entry.get("input_scale", "?"):.6f} in_zp={entry.get("input_zp", "?")} '
              f'out_s={entry.get("output_scale", "?"):.6f} out_zp={entry.get("output_zp", "?")}')

        conv_ops.append(entry)

    return conv_ops


def extract_tflite_params(tflite_path):
    """Load TFLite model and extract per-op quantization params."""
    try:
        import tensorflow as tf
        Interpreter = tf.lite.Interpreter
    except ImportError:
        try:
            from ai_edge_litert import interpreter as litert
            Interpreter = litert.Interpreter
        except ImportError:
            print('WARNING: No TFLite interpreter available, skipping TFLite extraction',
                  file=sys.stderr)
            return []

    interp = Interpreter(model_path=tflite_path)
    interp.allocate_tensors()

    details = interp.get_tensor_details()
    ops = interp._get_ops_details()

    print(f'\nTFLite: {len(details)} tensors, {len(ops)} ops')

    conv_ops = []
    for op_idx, op in enumerate(ops):
        op_name = op.get('op_name', '')
        if 'CONV_2D' not in op_name and 'DEPTHWISE_CONV_2D' not in op_name:
            continue

        inputs = op['inputs']
        outputs = op['outputs']

        act_detail = details[inputs[0]]
        act_qp = act_detail['quantization_parameters']
        w_detail = details[inputs[1]]
        w_qp = w_detail['quantization_parameters']
        out_detail = details[outputs[0]]
        out_qp = out_detail['quantization_parameters']

        entry = {
            'op_index': op_idx,
            'op_name': op_name,
            'weight_shape': w_detail['shape'].tolist(),
            'weight_dtype': str(w_detail['dtype']),
            'weight_scales': w_qp['scales'].tolist(),
            'weight_zps': w_qp['zero_points'].tolist(),
            'input_scale': float(act_qp['scales'][0]) if len(act_qp['scales']) else None,
            'input_zp': int(act_qp['zero_points'][0]) if len(act_qp['zero_points']) else None,
            'output_scale': float(out_qp['scales'][0]) if len(out_qp['scales']) else None,
            'output_zp': int(out_qp['zero_points'][0]) if len(out_qp['zero_points']) else None,
        }

        oc = w_detail['shape'][0]
        n_ws = len(w_qp['scales'])
        print(f'  [{op_idx:3d}] {op_name:25s} '
              f'w_shape={entry["weight_shape"]} '
              f'w_scales={n_ws}({"per-ch" if n_ws == oc else "per-tensor"}) '
              f'out_s={entry["output_scale"]:.6f} out_zp={entry["output_zp"]}')

        conv_ops.append(entry)

    return conv_ops


def match_and_compare(rknn_convs, tflite_convs):
    """Match RKNN conv nodes to TFLite conv ops and compare quant params."""
    print(f'\n{"=" * 70}')
    print(f'Matching {len(rknn_convs)} RKNN convs to {len(tflite_convs)} TFLite convs')
    print(f'{"=" * 70}\n')

    n = min(len(rknn_convs), len(tflite_convs))
    if len(rknn_convs) != len(tflite_convs):
        print(f'WARNING: count mismatch: RKNN={len(rknn_convs)} TFLite={len(tflite_convs)}')

    all_w_exact = 0
    all_o_exact = 0
    matched = []

    for i in range(n):
        rc = rknn_convs[i]
        tc = tflite_convs[i]

        # Compare weight scales
        r_ws = np.array(rc.get('weight_scales', []))
        t_ws = np.array(tc.get('weight_scales', []))
        if len(r_ws) == len(t_ws) and len(r_ws) > 0:
            abs_diff = np.abs(r_ws - t_ws)
            max_diff = float(np.max(abs_diff))
            if max_diff == 0:
                w_match = 'EXACT'
                all_w_exact += 1
            else:
                rel_diff = abs_diff / (np.abs(t_ws) + 1e-30)
                w_match = f'max_abs={max_diff:.2e} max_rel={float(np.max(rel_diff)):.2e}'
        elif len(r_ws) != len(t_ws):
            w_match = f'SIZE_MISMATCH r={len(r_ws)} t={len(t_ws)}'
        else:
            w_match = 'N/A'

        # Compare output scale
        r_os = rc.get('output_scale')
        t_os = tc.get('output_scale')
        if r_os is not None and t_os is not None:
            diff = abs(r_os - t_os)
            if diff == 0:
                o_match = 'EXACT'
                all_o_exact += 1
            else:
                o_match = f'diff={diff:.2e} (rknn={r_os:.8f} tfl={t_os:.8f})'
        else:
            o_match = f'N/A (rknn={r_os} tfl={t_os})'

        # Compare output zp
        r_zp = rc.get('output_zp')
        t_zp = tc.get('output_zp')
        zp_match = 'EXACT' if r_zp == t_zp else f'rknn={r_zp} tfl={t_zp}'

        # Compare input scale
        r_is = rc.get('input_scale')
        t_is = tc.get('input_scale')
        if r_is is not None and t_is is not None:
            i_diff = abs(r_is - t_is)
            in_match = 'EXACT' if i_diff == 0 else f'diff={i_diff:.2e}'
        else:
            in_match = f'N/A (rknn={r_is} tfl={t_is})'

        print(f'Conv {i:2d}: {rc["name"][:50]}')
        print(f'  weight_scales({len(r_ws)}): {w_match}')
        print(f'  input_scale:  {in_match}')
        print(f'  output_scale: {o_match}')
        print(f'  output_zp:    {zp_match}')

        match_entry = {
            'conv_index': i,
            'rknn_name': rc['name'],
            'rknn_node_index': rc['rknn_node_index'],
            'tflite_op_index': tc['op_index'],
            'tflite_op_name': tc['op_name'],
            'weight_shape': rc.get('weight_shape') or tc['weight_shape'],
            'weight_scales_match': w_match,
            'input_scale_match': in_match,
            'output_scale_match': o_match,
            'output_zp_match': zp_match,
            # Full params for downstream analysis
            'rknn_weight_scales': rc.get('weight_scales', []),
            'tflite_weight_scales': tc.get('weight_scales', []),
            'rknn_input_scale': r_is,
            'tflite_input_scale': t_is,
            'rknn_output_scale': r_os,
            'tflite_output_scale': t_os,
            'rknn_output_zp': r_zp,
            'tflite_output_zp': t_zp,
        }
        matched.append(match_entry)

    print(f'\nSummary: weight_scales EXACT={all_w_exact}/{n}, '
          f'output_scale EXACT={all_o_exact}/{n}')

    return matched


def grouping_analysis(matched):
    """Analyze how librocketnpu's per-channel grouping affects each conv."""
    print(f'\n{"=" * 70}')
    print('Per-Channel Grouping Analysis (group_size=16)')
    print(f'{"=" * 70}\n')
    GROUP_SIZE = 16

    for m in matched:
        t_wscales = np.array(m.get('tflite_weight_scales', []))
        w_shape = m.get('weight_shape', [0])
        oc = w_shape[0] if w_shape else 0

        if len(t_wscales) <= 1 or oc == 0 or len(t_wscales) != oc:
            continue

        n_groups = (oc + GROUP_SIZE - 1) // GROUP_SIZE

        # Unsorted grouping
        worst_unsorted = 1.0
        for g in range(n_groups):
            s, e = g * GROUP_SIZE, min((g + 1) * GROUP_SIZE, oc)
            gs = t_wscales[s:e]
            ratio = float(np.min(gs) / np.max(gs))
            worst_unsorted = min(worst_unsorted, ratio)

        # Sorted grouping (what librocketnpu does)
        sorted_scales = np.sort(t_wscales)
        worst_sorted = 1.0
        for g in range(n_groups):
            s, e = g * GROUP_SIZE, min((g + 1) * GROUP_SIZE, oc)
            gs = sorted_scales[s:e]
            ratio = float(np.min(gs) / np.max(gs))
            worst_sorted = min(worst_sorted, ratio)

        # Scale range
        scale_range = float(np.max(t_wscales) / np.min(t_wscales))

        improved = worst_sorted > worst_unsorted + 0.001
        print(f'Conv {m["conv_index"]:2d} ({oc:3d} ch, {n_groups:2d} grps): '
              f'range={scale_range:6.1f}x '
              f'worst unsorted={worst_unsorted:.4f} sorted={worst_sorted:.4f}'
              f'{" *" if improved else ""}')

        m['n_groups'] = n_groups
        m['worst_ratio_unsorted'] = worst_unsorted
        m['worst_ratio_sorted'] = worst_sorted
        m['scale_range'] = scale_range


def main():
    tflite_path = 'yolov5s_relu_int8.tflite'

    print('=' * 70)
    print('RKNN vs TFLite Quantization Parameter Extraction')
    print('=' * 70)

    # Step 1: Build RKNN to generate check0 ONNX (if not already present)
    onnx_path = build_rknn_and_get_onnx(tflite_path)

    # Step 2: Extract RKNN quant params from pre-fusion ONNX
    print(f'\n--- RKNN Conv Nodes (from {onnx_path}) ---')
    rknn_convs = extract_rknn_params(onnx_path)
    print(f'\nFound {len(rknn_convs)} RKNN conv nodes')

    # Step 3: Extract TFLite quant params
    print('\n--- TFLite Conv Ops ---')
    tflite_convs = extract_tflite_params(tflite_path)
    print(f'\nFound {len(tflite_convs)} TFLite conv ops')

    # Step 4: Match and compare
    matched = []
    if rknn_convs and tflite_convs:
        matched = match_and_compare(rknn_convs, tflite_convs)

    # Step 5: Grouping analysis
    if matched:
        grouping_analysis(matched)

    # Save JSON
    output = {
        'conv_ops': matched,
        'rknn_conv_count': len(rknn_convs),
        'tflite_conv_count': len(tflite_convs),
    }
    with open('quant_params.json', 'w') as f:
        json.dump(output, f, indent=2)
    print(f'\nSaved quant_params.json ({len(matched)} matched conv ops)')


if __name__ == '__main__':
    main()
